platform :ios, '13.0'
flutter_root = File.expand_path('..', File.dirname(__FILE__))

require '/Users/berkaygoksu/development/flutter/packages/flutter_tools/bin/podhelper'


target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
